### ISSUE TITLE
Please resubmit tt05-rule110 to Tiny Tapeout 05

### ISSUE THREAD

**Issue by urish** [rejunity/tt05-rule110#1]
Hi ReJ,

We have done some internal changes to Tiny Tapeout 05 that require resubmission of the project to the shuttle. It takes only two steps:

1. Rerun the [GDS workflow](https://github.com/rejunity/tt05-rule110/actions/workflows/gds.yaml) in this repo and wait for it to complete (or, if you create a new commit, that'll also start the GDS workflow)
2. Go to https://app.tinytapeout.com/ (sign in as needed), then choose the project click the blue "SUBMIT A NEW REVISION" button

Thanks!

**Comment by rejunity** [comment]
Done!
